language: node_js
node_js:
    - "8.9.4"
script:
    - "npm install -g pxt"
    - "pxt target microbit"
    - "pxt build --cloud"
sudo: false
cache:
    directories:
    - npm_modules
    - pxt_modules
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libusb-1.0-0-dev
env:
  - PXT_ENV=production CXX=g++-4.8